HOSTS:
  ubuntu--1404-x64:
    roles:
      - master
    platform: ubuntu-1404-amd64
    box: ubuntu/trusty64
    box_url: https://vagrantcloud.com/puppetlabs/boxes/ubuntu-14.04-64-nocm
    hypervisor: vagrant

CONFIG:
  log_level: verbose
  type: foss
  package_proxy: http://10.0.2.3:3128
